// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArqUzDk2I2KK24UVtH0kBILsJLbw6LGxM',
    appId: '1:81518144297:web:fb94691b2e504bd63fa538',
    messagingSenderId: '81518144297',
    projectId: 'study-app-6a82c',
    authDomain: 'study-app-6a82c.firebaseapp.com',
    storageBucket: 'study-app-6a82c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRkCEoXbsFcCL7AnBrcKY_X_UAwVkxgJ4',
    appId: '1:81518144297:android:50eccd1a006610d73fa538',
    messagingSenderId: '81518144297',
    projectId: 'study-app-6a82c',
    storageBucket: 'study-app-6a82c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7Dq7gPG-628Z9Sbp-j9-6C6QUn-LijU',
    appId: '1:81518144297:ios:981cfb22447f6cae3fa538',
    messagingSenderId: '81518144297',
    projectId: 'study-app-6a82c',
    storageBucket: 'study-app-6a82c.appspot.com',
    iosClientId: '81518144297-3g3nj41mf285fgh4r7ar5clp9d6i3d19.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHelpfulApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU7Dq7gPG-628Z9Sbp-j9-6C6QUn-LijU',
    appId: '1:81518144297:ios:981cfb22447f6cae3fa538',
    messagingSenderId: '81518144297',
    projectId: 'study-app-6a82c',
    storageBucket: 'study-app-6a82c.appspot.com',
    iosClientId: '81518144297-3g3nj41mf285fgh4r7ar5clp9d6i3d19.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHelpfulApp',
  );
}
